apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx
  # these labels are replicaset labels
  labels: 
    purpose: dp-demo
    project: roboshop
spec:
  replicals: 4
  selector:
    # these labels are used to select pods
    matchLables:
      purpose: headless-svc-demo
      project: roboshophop
  # pod definition
  template:
    metadata:
      lables:
      purpose: headless-svc-demo
      project: roboshop
    spec:
      containers:
      - name: nginx
        image: nginx:latest


---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    purpose: headless-svc-demo
    project: roboshop
  ports:
    - protocal: TCP
      port: 80 #service port
      targetPort: 80 #container port

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
spec:
  # if a service ClusterIP then it is called headless service
  clusterIP: none 
  selector:
    purpose: headless-svc-demo
    project: roboshop
  ports:
    - protocal: TCP
      port: 80 #service port
      targetPort: 80 #container port